gitpod config

diff --git a/.gitpod.yml b/.gitpod.yml
--- a/.gitpod.yml
+++ b/.gitpod.yml
@@ -1,5 +1,3 @@
-image: gitpod/workspace-ruby:3.1
-
 ports:
   - port: 3000
     onOpen: ignore
@@ -19,6 +17,9 @@ tasks:
       exit
   - name: Forem Server
     before: |
+      git fetch origin
+      git checkout integration-branch || echo "Branch not found, staying on default branch"
+      git pull
       cp .env_sample .env
       echo "APP_DOMAIN=\"$(gp url 3000 | cut -f 3 -d /)\"" >> .env
       echo 'APP_PROTOCOL="https://"' >> .env
